In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('/content/paises.csv', sep =';')
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000

In [6]:
#Faça um slicing no dataset para mostrar apenas o País (Country), Região
#(Region), População (Population) e Area (Area (sq. mi.)) dos países contidos
#nele
colunas = df[['Country', 'Region', 'Population', 'Area (sq. mi.)']]
colunas.head()

,Country,Region,Population,Area (sq. mi.)
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500
1,Albania,EASTERN EUROPE,3581655,28748
2,Algeria,NORTHERN AFRICA,32930091,2381740
3,American Samoa,OCEANIA,57794,199
4,Andorra,WESTERN EUROPE,71201,468

In [7]:
#Diferentes regioes do planeta
df['Region'].value_counts()

Region
SUB-SAHARAN AFRICA                     51
LATIN AMER. & CARIB                    45
ASIA (EX. NEAR EAST)                   28
WESTERN EUROPE                         28
OCEANIA                                21
NEAR EAST                              16
EASTERN EUROPE                         12
C.W. OF IND. STATES                    12
NORTHERN AFRICA                         6
NORTHERN AMERICA                        5
BALTICS                                 3
Name: count, dtype: int64

In [8]:
#Mostre qual a taxa média de alfabetização (Literacy (%)) do planeta segundo
media = df['Literacy (%)'].mean()
print(media)

76.2696035242291

In [21]:
#Conte quantos países são da América do Norte (NORTHERN AMERICA)
northern_america_countries = df[df['Region'].str.strip() == 'NORTHERN AMERICA']
num_northern_america = len(northern_america_countries)
print(f"Número de países na NORTHERN AMERICA: {num_northern_america}")

Número de países na NORTHERN AMERICA: 5

In [20]:
#Encontre qual país da América do Sul e Caribe (LATIN AMER. & CARIB)
df['Region'] = df['Region'].str.strip()
america_latina_caribe = df[df['Region'] == 'LATIN AMER. & CARIB']
pais_mais_rico_america_latina = america_latina_caribe.loc[america_latina_caribe['GDP ($ per capita)'].idxmax()]
print(f"{pais_mais_rico_america_latina['Country']} com GDP de {pais_mais_rico_america_latina['GDP ($ per capita)']}$")

Cayman Islands  com GDP de 35000$